### ISSUE TITLE
User Can See Their Car

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an HTML and CSS skeleton 
  - [x] Add the car SVG and background-color
- [x] Create a Car object in main.js file
  - [x] Add method names for the car
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
