### ISSUE TITLE
User Can Choose Between Different Car Models.

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/driving-game#10]
## 💰 Motivation

Not everyone wants to be a racecar driver. Let them just cruise down the PCH!

## 📐 Plan

Give the user the option to change the car model.

## ✅ Task List

- [x] Find a few (3 more?) car images that shows the car from the top-down view.
  - [x] Add all image files into the /images folder.
- [x] Remove img tag from HTML and add prompt window (div).
  - [x] Include text in the div: "Which car would you like to drive?".
  - [x] Include a dropdown menu listing all car models.
  - [x] Style the new HTML elements.
  - [x] Query dropdown menu & create img element & append to body.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x]  Fix all errors.
