### ISSUE TITLE
User Can Turn Their Car

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model that represents the direction the car is facing.
  - [x] 0 for right, 90 for down, 180 for left, -90 for up.
- [x] Query the DOM element for the car.
- [x] Listen for the 'keydown' event.
  - [x] Transform & rotate to the position depending on the event.
  - [x] Allow a transition animation when car is rotating
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x]  Test all functionality.
- [x]  Fix all errors.
