### ISSUE TITLE
User Can Start Their Car

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a location to your data model to hold the car's x and y coordinates on the page.
  - [x] Rename data model object accordingly.
- [x] Make the car positioned absolutely.
- [x] Append the style property to the car html element.
  - [x] Update the car's position with left and top depending on the way the car is facing.
  - [x] Smoothen the animation with 'setInterval' every 16ms.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
