### ISSUE TITLE
User Can Stop Their Car

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean check to your data model to indicate whether or not the car is started.
  - [x] Add a conditional statement to stop the car when pressing 'space' again.
  - [x] Make sure the car retains the direction it's facing when stopping.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x]  Fix all errors.
