### ISSUE TITLE
User Can Steer Their Car

### ISSUE THREAD

**Issue by theDanielTo** [theDanielTo/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Alter startCar function to allow movement change with 'keydown' event
  - [x] Reset setInterval to only allow horizontal & vertical movement
  - [x] Add boolean to check for car movement during steer
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
- [x]  Fix all errors.
